os:
  - linux
  - osx
language: node_js
node_js:
  - '4'
  - '6'
  - '8'
before_script:
  - npm install winston@2.3.0 --production
  - 'npm install https://github.com/ioBroker/ioBroker.js-controller/tarball/master --production'
  - npm install iobroker.web  --prefix ./node_modules/iobroker.js-controller/ --production
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
